version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Logging into AWS ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nodeapp:latest .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nodeapp:latest
      - echo Build completed on `date`